name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: luci1927
          outputs: dist/snake.svg

      - name: Commit and Push Snake Animation
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mkdir -p output
          chmod -R 777 output
          mv dist/snake.svg output/github-contribution-grid-snake.svg
          git checkout main
          git add output/github-contribution-grid-snake.svg
          git commit -m "Updated Snake Animation" || echo "No changes to commit"
          git push
